### ISSUE TITLE
Environment variable LC_ALL in cmake formula

### ISSUE THREAD

**Issue by xgarrido** [SuperNEMO-DBD/cadfaelbrew#2]
I had big problems when installing cadfael due to the following line https://github.com/SuperNEMO-DBD/cadfaelbrew/blob/master/Library/Formula/cmake.rb#L67 that basically screwed up all the installation process. I am under archlinux 

```sh
$ uname -a
Linux garrido-laptop 4.2.2-1-ARCH #1 SMP PREEMPT Tue Sep 29 22:21:33 CEST 2015 x86_64 GNU/Linux
```

and maybe my `locale` settings are not properly done but commenting this line solves the issue and cadfael installation went smoothly until the end. I also had a look into http://bugs.python.org/issue18378#msg21521 and the result of `locale` gives me

```sh
LANG=fr_FR.UTF-8
LC_CTYPE=fr_FR.UTF-8
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

Maybe settings `LC_ALL` to "en_US.UTF-8" conflicts with "fr_FR.UTF-8" ??

**Comment by drbenmorgan** [comment]
The setting of `LC_ALL` in the Formula is Mac specific, so could (should!) be protected for Linux, and I suspect it's the conflict you note that causes the issue. I'll also get a docker image for Arch up and running.

**Comment by xgarrido** [comment]
When reinstalling cadfael things, I have fixed this problem on my side by uncommenting the "en_US.UTF-8" string within ```/etc/locale.gen``` file and then doing ```sudo locale-gen```.
