### ISSUE TITLE
Unable to complete cadfael-bootstrap - think python 2.7.11 did not install

### ISSUE THREAD

**Issue by cherylepatrick** [SuperNEMO-DBD/cadfaelbrew#3]
# Please follow the general troubleshooting steps first:

- [ Y] Ran `brew update` and retried your prior step?
- [ Y] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ N/A] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
(Also I do not have sudo access)

### Bug reports:
Brew is not finding python 2.7 but it thinks it is installed (brew install -v python says 2.7.11 but if I run python from the command line, it is 2.6.6). This is after a previous error where it failed to find the python 2.7.11 directory so I created it in CadfaelBrew/Cellar (probably foolishly). Next time I ran brew it failed, but told me to brew link python which I also (probably foolishly) did. I dunno if the presence of that (empty( python 2.7.11 directory is why it thinks that python 2.7.11 is installed.

`brew gist-logs cadfael-bootstrap`
... doesn't work, I guess cadfael-bootstrap is not a formula? 
This is the command it is now failing on python -c import setuptools... --no-user-cfg install --prefix=/home/cpatrick/CadfaelBrew/Cellar/sphinx-d

It can't find the option --no-user-cfg install  and that is because it is using /usr/bin/python which is 2.6.6:
Result of cat /home/cpatrick/.cache/Homebrew/Logs/sphinx-doc/01.python:

2016-04-26 11:55:56 +0100

python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/home/cpatrick/CadfaelBrew/Cellar/sphinx-doc/1.3.4/libexec/vendor
--single-version-externally-managed
--record=installed.txt

usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: -c --help [cmd1 cmd2 ...]
   or: -c --help-commands
   or: -c cmd --help

error: option --no-user-cfg not recognized

HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/SuperNEMO-DBD/cadfaelbrew.git
HEAD: 0603a89b752e22a3f189f6b998789db7b3971fc7
Last commit: 37 minutes ago
HOMEBREW_PREFIX: /home/cpatrick/CadfaelBrew
HOMEBREW_REPOSITORY: /home/cpatrick/CadfaelBrew
HOMEBREW_CELLAR: /home/cpatrick/CadfaelBrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: dual-core 64-bit 0xf43
Kernel: Linux 2.6.32-431.el6.x86_64 x86_64 GNU/Linux
OS: Scientific Linux release 6.5 (Carbon)
Codename: Carbon
OS glibc: 2.12
OS gcc: 4.4.7
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Clang: N/A
X11: 2.7.8 => /usr
System Ruby: 2.2.3 => /home/cpatrick/CadfaelBrew/Cellar/ruby/2.2.3/bin/ruby
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /home/cpatrick/CadfaelBrew/bin/ruby => /home/cpatrick/CadfaelBrew/Cellar/ruby/2.2.3/bin/ruby
Java: 1.7.0_101

CC: /home/cpatrick/CadfaelBrew/bin/gcc-4.9 => /home/cpatrick/CadfaelBrew/Cellar/gcc49/4.9.3/bin/gcc-4.9
CXX: /home/cpatrick/CadfaelBrew/bin/g++-4.9 => /home/cpatrick/CadfaelBrew/Cellar/gcc49/4.9.3/bin/g++-4.9
OBJC: /home/cpatrick/CadfaelBrew/bin/gcc-4.9
OBJCXX: /home/cpatrick/CadfaelBrew/bin/g++-4.9
CFLAGS: -Os -w -pipe -march=core2
CXXFLAGS: -Os -w -pipe -march=core2
CPPFLAGS: -isystem/home/cpatrick/CadfaelBrew/include
LDFLAGS: -L/home/cpatrick/CadfaelBrew/lib -Wl,--dynamic-linker=/home/cpatrick/CadfaelBrew/lib/ld.so -Wl,-rpath,/home/cpatrick/CadfaelBrew/lib
MAKEFLAGS: -j2
CMAKE_PREFIX_PATH: /home/cpatrick/CadfaelBrew
PKG_CONFIG_LIBDIR: /home/cpatrick/CadfaelBrew/lib/pkgconfig
PATH: /home/cpatrick/CadfaelBrew/opt/python/bin:/home/cpatrick/CadfaelBrew/bin:/home/cpatrick/CadfaelBrew/bin:/home/cpatrick/CadfaelBrew/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/maui/bin:/home/cpatrick/bin:/home/cpatrick/CadfaelBrew/Library/Taps/supernemo-dbd/homebrew-cadfael/cmd:/home/cpatrick/CadfaelBrew/Library/ENV/scm

Can I just try brew installing python 2.7.11?

**Comment by drbenmorgan** [comment]
Yes, I'd try just 

```console
brew install python
```

in the first case. Whilst the environment looks o.k., do you have `/home/cpatrick/CadfaelBrew/bin` at the front of your `PATH` when running `brew`?

**Comment by cherylepatrick** [comment]
Yep, I have that directory at the front of the PATH but there's no python in there. Will try installing python and see what happens, thanks Ben.

**Comment by cherylepatrick** [comment]
Still no luck installing python. Log gist is here:
https://gist.github.com/anonymous/16d9c62132ec9c98674b388ce254f8b2

Brew doctor suggests removing some files from /usr/local/include but I don't have permissions to do so.

The part where it fails is:
==> make install PYTHONAPPSDIR=/home/cpatrick/CadfaelBrew/Cellar/python/2.7.11
Creating directory /home/cpatrick/CadfaelBrew/Cellar/python/2.7.11/bin
/usr/bin/install -c python /home/cpatrick/CadfaelBrew/Cellar/python/2.7.11/bin/python2.7
if test -f libpython2.7.so; then \
if test -n "" ; then \

/usr/bin/install -c -m 555  /home/cpatrick/CadfaelBrew/Cellar/python/2.7.11/bin; \


else \

/usr/bin/install -c -m 555 libpython2.7.so /home/cpatrick/CadfaelBrew/Cellar/python/2.7.11/lib/libpython2.7.so.1.0; \


if test libpython2.7.so != libpython2.7.so.1.0; then \


(cd /home/cpatrick/CadfaelBrew/Cellar/python/2.7.11/lib; ln -sf libpython2.7.so.1.0 libpython2.7.so) \



fi \


fi; \

else true; \
fi
/bin/sh: line 6:  5126 Illegal instruction     LD_LIBRARY_PATH=/tmp/python20160426-25662-vqca7y/Python-2.7.11:/home/cpatrick/CadfaelBrew/Cellar/python/2.7.11/lib CC='/home/cpatrick/CadfaelBrew/bin/gcc-4.9 -pthread' LDSHARED='/home/cpatrick/CadfaelBrew/bin/gcc-4.9 -pthread -shared -L/home/cpatrick/CadfaelBrew/opt/openssl/lib -L/home/cpatrick/CadfaelBrew/opt/readline/lib -L/home/cpatrick/CadfaelBrew/opt/sqlite/lib -L/home/cpatrick/CadfaelBrew/opt/gdbm/lib -L/home/cpatrick/CadfaelBrew/lib' OPT='-DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes' _TCLTK_INCLUDES='' _TCLTK_LIBS='' ./python -E ./setup.py $quiet build
make: *** [sharedmods] Error 132
==> Formula
Path: /home/cpatrick/CadfaelBrew/Library/Formula/python.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/SuperNEMO-DBD/cadfaelbrew.git
HEAD: 0603a89b752e22a3f189f6b998789db7b3971fc7
Last commit: 2 hours ago
HOMEBREW_PREFIX: /home/cpatrick/CadfaelBrew
HOMEBREW_REPOSITORY: /home/cpatrick/CadfaelBrew
HOMEBREW_CELLAR: /home/cpatrick/CadfaelBrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: dual-core 64-bit 0xf43
Kernel: Linux 2.6.32-431.el6.x86_64 x86_64 GNU/Linux
OS: Scientific Linux release 6.5 (Carbon)
Codename: Carbon
OS glibc: 2.12
OS gcc: 4.4.7
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Clang: N/A
X11: 2.7.8 => /usr
System Ruby: 2.2.3 => /home/cpatrick/CadfaelBrew/Cellar/ruby/2.2.3/bin/ruby
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /home/cpatrick/CadfaelBrew/bin/ruby => /home/cpatrick/CadfaelBrew/Cellar/ruby/2.2.3/bin/ruby
Java: 1.7.0_101
==> ENV
CC: /home/cpatrick/CadfaelBrew/bin/gcc-4.9 => /home/cpatrick/CadfaelBrew/Cellar/gcc49/4.9.3/bin/gcc-4.9
CXX: /home/cpatrick/CadfaelBrew/bin/g++-4.9 => /home/cpatrick/CadfaelBrew/Cellar/gcc49/4.9.3/bin/g++-4.9
OBJC: /home/cpatrick/CadfaelBrew/bin/gcc-4.9
OBJCXX: /home/cpatrick/CadfaelBrew/bin/g++-4.9
CFLAGS: -Os -w -pipe -march=core2
CXXFLAGS: -Os -w -pipe -march=core2
CPPFLAGS: -isystem/home/cpatrick/CadfaelBrew/include
LDFLAGS: -L/home/cpatrick/CadfaelBrew/lib -Wl,--dynamic-linker=/home/cpatrick/CadfaelBrew/lib/ld.so -Wl,-rpath,/home/cpatrick/CadfaelBrew/lib
CMAKE_PREFIX_PATH: /home/cpatrick/CadfaelBrew
PKG_CONFIG_LIBDIR: /home/cpatrick/CadfaelBrew/lib/pkgconfig
PATH: /home/cpatrick/CadfaelBrew/bin:/home/cpatrick/CadfaelBrew/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/maui/bin:/home/cpatrick/bin:/home/cpatrick/CadfaelBrew/Library/Taps/supernemo-dbd/homebrew-cadfael/cmd:/home/cpatrick/CadfaelBrew/Library/ENV/scm

Error: python 2.7.11 did not build
Logs:
     /home/cpatrick/.cache/Homebrew/Logs/python/01.configure
     /home/cpatrick/.cache/Homebrew/Logs/python/config.log
     /home/cpatrick/.cache/Homebrew/Logs/python/03.make
     /home/cpatrick/.cache/Homebrew/Logs/python/02.make

**Comment by cherylepatrick** [comment]
I noticed this in some of the log output, will investigate:

Python build finished, but the necessary bits to build these modules were not found:
bsddb185           dl                 imageop         
sunaudiodev                                           
To find the necessary bits, look in setup.py in detect_modules() for the module's name.

Failed to build these modules:
bz2                dbm

**Comment by drbenmorgan** [comment]
The only things in the list that wasn't built that *might* affect later things are `dl` and `bz2` parts. Certainly `bz2` is odd because the Python formula explicitly depends on the bzip2 formula (does `brew ls` list `bzip2` as installed?)
 
One further possibility is that the `-march=core2` isn't appropriate for the CPU in this machine (looks like Xeon from the `0xf43` Id). Could you try applying this change

https://github.com/Linuxbrew/linuxbrew/pull/1094/commits/fce4e73f5c7509c331d1f12499eceaa66c93b536

and then do (*be careful not to update otherwise the change may be wiped!*)

```console
$ brew install -v python
... Use -v and check the appropriate flags "-march=native" are applied...
```

If that still fails, then I would try rebuilding everything by doing

```console
$ brew rm $(brew ls)
$ brew install ruby git
$ brew install gcc49
$ brew install python
```

If that all goes o.k. do

```console
$ brew install ninja cmake git-flow-avh falaise
```

which completes what the bootstrap script does

**Comment by cherylepatrick** [comment]
Thanks Ben, the change you linked worked perfectly. Everything's installed now. Only other thing I was missing was GNU m4 but there was no problem in adding it. Thanks again for your help!

**Comment by drbenmorgan** [comment]
Thanks for the update @cherylepatrick! I'll get the patch into cadfaelbrew assuming it doesn't (and shouldn't) break anything on mac. 

Also, where did the error/warning about needing `m4` pop up? Just wondering if it needs adding to the list of required system packages, or an additional ``depends_on`` is needed in a Formula.

**Comment by cherylepatrick** [comment]
Thanks Ben, the change you linked worked perfectly. Everything's installed now. Only other thing I was missing was GNU m4 but there was no problem in adding it. Thanks again for your help!

**Comment by cherylepatrick** [comment]
I think the m4 thing was a prerequisite for bison, which was a prereq for falaise.
